### ISSUE TITLE
Doesn't work in the browser anymore because of node fs call

### ISSUE THREAD

**Issue by rasdaniil** [evanshortiss/env-var#10]
Hi!
Version 3.0 now requires fs to be present and it stops it from working in the browser via webpack (at least without applying magic)

https://github.com/evanshortiss/env-var/blob/46ae1a7f5e559554b08a9fa6b9e5e31794c6e08a/lib/variable.js#L58

Instead of reading the accessors directory maybe it would be possible just to keep a list of accessors in a variable.. 

Thanks for the effort

**Comment by evanshortiss** [comment]
@rasdaniil interesting, I did not think this module would be used in the browser! Are you using it with browserify or webpack and injecting some `process.env`?

What is your use case if you don't mind me asking?

**Comment by evanshortiss** [comment]
@rasdaniil can you try `npm install evanshortiss/env-var#browser-fix` adn let me know if it resolves your issue? If so I can publish it. I've tested with browserify here and have it working as shown in this screenshot, but want to make sure it's fixed for your setup too:

![screen shot 2017-10-18 at 15 48 29](https://user-images.githubusercontent.com/1303687/31746908-9a73190e-b41e-11e7-8573-507b61c6bc57.png)

I bundled it using the command `browserify ./env-var.js -o test-browserify.js -s envvar` and then loaded it in Chrome.

**Comment by evanshortiss** [comment]
@rasdaniil think all should be good now if you install `npm install env-var@3.0.3`

**Comment by rasdaniil** [comment]
Hi!
Thanks a lot for reply! I've just now got round to checking my email
I'll give it a try shortly

**Comment by evanshortiss** [comment]
@rasdaniil awesome - did something similar before, but didn't use this module! Also, my previous comment should have stated version `3.0.2`
