### ISSUE TITLE
.asIntPositive/Negative both true for 0

### ISSUE THREAD

**Issue by joh-klein** [evanshortiss/env-var#103]
To quote from the docs:

> asIntPositive()
Performs the same task as asInt(), but also verifies that the number is positive (greater than zero).
>
> asIntNegative()
Performs the same task as asInt(), but also verifies that the number is negative (less than zero).

This is very close to what the [Wikipedia entry says about integers](https://en.wikipedia.org/wiki/Integer#Order-theoretic_properties) with the important addition, that zero is neither:

> An integer is positive if it is greater than zero and negative if it is less than zero. Zero is defined as neither negative nor positive.

But when I look in the code, [here](https://github.com/evanshortiss/env-var/blob/master/lib/accessors/int-negative.js#L8) and [here](https://github.com/evanshortiss/env-var/blob/master/lib/accessors/int-positive.js#L8) you specifically leave out `0` which makes it both positive and negative.

I actually don't mind that, I would only like it, if it said so in the docs :)

**Comment by evanshortiss** [comment]
@joh-klein included in v6.0.2 release 😄
