### ISSUE TITLE
is it possible to use nested settings in "from"

### ISSUE THREAD

**Issue by WuglyakBolgoink** [evanshortiss/env-var#111]
Hi, 

is it possible to get value from nested json file if I use `env.from({...})`?

Example:

```json
{
    "API_BASE_URL": {
        "DEVELOP": "https://develop-server.com/api",
        "STAGING": "https://staging-server.com/api",
        "PROD": "https://production-server.com/api"
    },
    ...
}
```

Currently I have an error: `EnvVarError: env-var: "API_BASE_URL.DEVELOP" is a required variable, but it was not set`

What I do:

```
...
const envConfig = require('./config.env.json');
const env = require('env-var').from(envConfig);
...
API_BASE_URL = env.get('API_BASE_URL.DEVELOP').required().asUrlString()
...
```

**Comment by evanshortiss** [comment]
Currently, no this isn't supported. The `from` function expects an Object similar to `process.env` will be passed.

In your case here, would it make more sense to have a separate set of files like:

* develop.env.json
* develop.env.json

**Comment by evanshortiss** [comment]
> expects an Object similar to `process.env`

By this I mean key-value pairs where the value is a string.

**Comment by WuglyakBolgoink** [comment]
Hallo @evanshortiss !
yes... I think it will be better to have separate configs too. thank you!
