### ISSUE TITLE
Add generic type to asEnum

### ISSUE THREAD

**Issue by moltar** [evanshortiss/env-var#116]
Would be great to have a generic type available for `asEnum` method.

https://github.com/evanshortiss/env-var/blob/7ff513820f8650aed1370cef681200c5c299cc04/env-var.d.ts#L120

Should be:

```ts
 asEnum: <T extends string>(validValues: T[]) => T;
```

This would allow to pass arrays with custom types, e.g. string unions.

**Comment by evanshortiss** [comment]
Neat idea @moltar. Interested in making a PR?
