### ISSUE TITLE
ExtenderType, ExtenderTypeOptional do not satisfy the constraint

### ISSUE THREAD

**Issue by moltar** [evanshortiss/env-var#119]
**Describe the bug 🐛**

I think 34759d2eb3d96602be372537b0e0392e1d03ae7d introduced a bug to TS definitions.

```
(type parameter) T in type ExtenderType<T>
Type 'T[P]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T[keyof T]' is not assignable to type '(...args: any) => any'.
    Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(...args: any) => any'.
      Type 'T[string]' is not assignable to type '(...args: any) => any'.ts(2344)
```

**To Reproduce 📝**

Build failure:

https://github.com/ScaleLeap/config/pull/44/checks?check_run_id=602773264

But also just inspecting the `env-var.d.ts` will display the errors in VS Code.

**Expected behaviour 🤷‍♂️🤷**

No errors.

**Screenshots 📷**

<img width="1163" alt="Screen-Shot-2020-04-21-16-03-16" src="https://user-images.githubusercontent.com/491247/79847236-a067d780-83e9-11ea-9f4f-d2b60a6a6377.png">

**Environment (please complete the following information) 💻:**
 - OS: macOS
 - Runtime: VS Code, CLI
 - Version:

```
❯ tsc -v
Version 3.8.3
```

```
❯ node -v
v12.16.0
```

**Additional context**

N/A

**Comment by evanshortiss** [comment]
Thanks for reporting this an apologies for the bugged release. I'll need to look into why my tests didn't run into this.

**Comment by evanshortiss** [comment]
@moltar can you share your tsconfig?

I'm not getting this error after using TS 3.8 and reinstalling all modules.

**Comment by evanshortiss** [comment]
Nevermind, I recreated the issue in a separate repo.

**Comment by evanshortiss** [comment]
@moltar can you test the 6.x branch with your application? I believe it resolves the issue.

**Comment by moltar** [comment]
@evanshortiss thank you for the prompt action!

I have tested the build with `6.x` branch and it seems to work well and TypeScript compiles.

**Comment by evanshortiss** [comment]
Likewise, thank you for the report. 

I'll need to look into the testing, since I want these things to be caught by CI! It seems like I need a separate project or something to fully test, since the sample I use in this repo clearly isn't doing the trick.
