### ISSUE TITLE
Release 6.1.1 to NPM

### ISSUE THREAD

**Issue by EntropyAu** [evanshortiss/env-var#122]
Many thanks for supporting this package! I was hoping to check if version 6.1.1 will be published to NPM (currently 6.1.0 is published, which causes build failures with Typescript).

**Comment by evanshortiss** [comment]
Oh wow @EntropyAu my bad. I was traveling the past two days and didn't notice my publish failed when I tried last time - it's been a crazy few days!

I have successfully published now. Thank you for alerting me to this issue.
