### ISSUE TITLE
Typo in repo description 'sanatization'

### ISSUE THREAD

**Issue by DigiPie** [evanshortiss/env-var#127]
**Describe the bug 🐛**

There's a typo in the repository description:

"Verification, **sanatization**, and type coercion for environment variables in Node.js"

**To Reproduce 📝**
N/A

**Expected behaviour 🤷‍♂️🤷**
It should be 'sanitization' instead.

**Screenshots 📷**
N/A

**Environment (please complete the following information) 💻:**
N/A

**Additional context**
Thanks for writing and maintaining this npm module. Love it!

**Comment by evanshortiss** [comment]
@DigiPie, good eye. I fixed it now. I'd argue it should be "sanitisation" with an "s" too, but I'll leave it with a "Z" for now haha!
