### ISSUE TITLE
Feature request: asRegExp()

### ISSUE THREAD

**Issue by ineentho** [evanshortiss/env-var#134]
Sometimes it it would be useful to be able to parse an environment variable into a regular expression. A common use case for me is a pattern for whitelisted CORS hosts.

My suggested api would be:

```
.asRegExp(flags = undefined)
```

where the environment variable should be passed to the first (pattern) parameter of the RegExp constructor and the flags as the second parameter.

Including regular expression support would be nice as there is some error checking for invalid regexps could be included in the library rather than each application.

If you would conciser including this feature, I'd gladly contribute a pull request.

**Comment by evanshortiss** [comment]
Agreed this would be a useful feature. I wonder...would it make sense to make `asString()` accept these args?

**Comment by ineentho** [comment]
IMO a separate method would make more sense. `asString()` implies that the result is a string, while `asRegExp()` would make it clear that the result is a RegExp.

**Comment by evanshortiss** [comment]
Oh sorry, I misunderstood. The returned result is a `RegExp` instance! It definitely makes sense to be a separate function as you say.

Happy to accept a PR for this 👍

**Comment by evanshortiss** [comment]
Included in v6.3.0
