### ISSUE TITLE
Add 'example/README.md'

### ISSUE THREAD

**Issue by DigiPie** [evanshortiss/env-var#135]
**Is your feature request related to a problem? Please describe.**
Currently, the README.md at the project root is quite long and verbose. For me, and maybe others, it is quite hard to sieve through all the information.

**Describe the solution you'd like**
I was thinking of creating an 'example/README.md' which will:

- Provide brief details on the example files available under 'example/'
- Contain some of the example content shifted over from 'README.md' to this new file
  - With links added to the original 'README.md' at appropriate points leading to their corresponding relevant sections in 'example/README.md'

**Describe alternatives you've considered**
Refactor the existing 'README.md' and remove less important content. I already did a quick look-through and most details in it should be shown somewhere in my opinion, just maybe shifted to a secondary 'README.md' file for further reference.

**Additional context**
Let me know what you think!

**Comment by evanshortiss** [comment]
100% agree. Every time I open the README I think "oh no, it's gotten even more bloated" 😆

An `examples/README.md` is a great idea. Allows the primary README focus on the API, and just provide links to sections of `examples/README.md`.

I'd love to see a PR for this.

**Comment by DigiPie** [comment]
> 100% agree. Every time I open the README I think "oh no, it's gotten even more bloated" 😆
> 
> An `examples/README.md` is a great idea. Allows the primary README focus on the API, and just provide links to sections of `examples/README.md`.
> 
> I'd love to see a PR for this.

Alright I'll work on it sometime next week and raise the PR then 😄

**Comment by evanshortiss** [comment]
@DigiPie did you ever get to look into this? I'm prepping a 7.x release, so if you have anything worked on I'd be happy to see if we can work it into 7.0.0.

**Comment by DigiPie** [comment]
@evanshortiss oh this slipped my mind 😅 I'll work on it today and raise a PR soon.
