### ISSUE TITLE
The number accessors are too permissive

### ISSUE THREAD

**Issue by jerome-fox** [evanshortiss/env-var#143]
**Describe the bug 🐛**
The number accessors are too permissive.
The `parseInt` and `parseFloat` functions allow strings beginning with numbers.

**To Reproduce 📝**
```javascript
parseInt('123hello') // 123
parseFloat('192.168.1.1') // 192.168
```

**Expected behaviour 🤷‍♂️🤷**
Sending '123hello' or '192.168.1.1' should throw an exception

**Additional context**
The solution could be to check if the parsed value is stringify, it should be the same as the input value.
I've a PR ready if you're interested.

**Comment by evanshortiss** [comment]
@jerome-fox sure, happy to take a look at the PR! 

A regex might do the trick too? Something like:

```js
const numbers = 'a123'.match(/^[0-9]*$/)

if (numbers === null) {
  // Error, string contained non numeric characters
}
```

**Comment by jerome-fox** [comment]
@evanshortiss I made the PR #144 
A regex do the trick too.

My solution has one problem : if a number starts or ends with some `0` characters

`00234` will be parsed has `234` but as string it will be `234` and not `00234`
we should trim the string to remove unnecessary `0` characters (but keep one `0` if the number is `0` or `0.xxx`)
I put aside this problem because I think that we do not really give a number with unnecessary `0`
But the solution with 2 regex (one for integer `/^[0-9]+$/` and one for float `/^[0-9]+(\.[0-9]+)?$/`) fixes this problem

**Comment by evanshortiss** [comment]
Thanks @jerome-fox will create a patch release shortly!
