### ISSUE TITLE
Duplicate identifier 'EnvVarError'.

### ISSUE THREAD

**Issue by moltar** [evanshortiss/env-var#152]
**Describe the bug 🐛**

Got the following errors on the latest version (v7.1.0):

```
Error: node_modules/env-var/env-var.d.ts(263,14): error TS2300: Duplicate identifier 'EnvVarError'.
Error: node_modules/env-var/env-var.d.ts(308,14): error TS2300: Duplicate identifier 'EnvVarError'.
```

**To Reproduce 📝**

N/A

**Expected behaviour 🤷‍♂️🤷**

Not to get TS build errors.

**Screenshots 📷**

N/A

**Environment (please complete the following information) 💻:**

N/A

**Additional context**

N/A

**Comment by evanshortiss** [comment]
@Lioness100 all good. CI **should** have caught it!
