### ISSUE TITLE
TypeError: env.get is not a function

### ISSUE THREAD

**Issue by ES41** [evanshortiss/env-var#154]
**Describe the bug 🐛**
getting this error when trying to get environment variable using the package 
```
file:///x/index.js:3
const PORT = env.get('PORT').default('5432').asString();
                 ^

TypeError: env.get is not a function
    at file:///private/tmp/test/index.js:3:18
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```
**To Reproduce 📝**
see code snippets added in `Additional context`

**Expected behaviour 🤷‍♂️🤷**
variable `PORT` having value and not crush the proccess

**Environment (please complete the following information) 💻:**
 - OS: MAC
 - Runtime NodeJS
 - Version 16.15.1

**Additional context**
`index.js`
```
import * as env from "env-var"

const PORT = env.get('PORT').default('5432').asString();
console.log(PORT)
```

`package.json`
```
  "main": "index.js",
  "type": "module",
```

`npm ls`
```
test@1.0.0 /x
└── env-var@7.1.1
```

**Comment by evanshortiss** [comment]
Can you try `import env from 'env-var' instead? That seems to work for me.

Seems like it's related to using ESM via `"type":"module"`. I haven't dived into that ESM module mess yet, but seems like a quick update to the README would be helpful?

**Comment by ES41** [comment]
> 
seems to fix the issue !

from `README.md`:
```
// Or using import syntax:
// import * as env from 'env-var'
```
should be 
```
// Or using import syntax:
// import env from 'env-var'
```
