### ISSUE TITLE
Client side.

### ISSUE THREAD

**Issue by ted-dino** [evanshortiss/env-var#162]
I don't sure if this has been asked before, but can this package access environment variables on the client side? I tried to print the env variable to the console, but it said it was `undefined`, even though I could see what it printed in the terminal. I know I'm terrible at explaining, but maybe the image i've included may help.

![bad-at-explaining](https://user-images.githubusercontent.com/84649871/189062857-f94d8432-697c-481d-a3ac-938d4f3b2fc2.png)

**Comment by evanshortiss** [comment]
This seems to be related with how Next.js handles `process.env`. It says [here in the docs ](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser) that they inline the value to the browser. They also explicitly state that "dynamic lookups will not be inlined".

Based on my understanding, this means that if your code is:

```js
const url = process.env.NEXT_PUBLIC_BASE_URL
```

Next.js compiles it to:

```js
const url = 'http://localhost:3000'
```

You need to explicitly make a call to `process.env.NEXT_PUBLIC_BASE_URL` someplace for it to be replaced by their compilation steps.

Using this knowledge I found **the following example works** when using env-var:

```js
import { from } from 'env-var'

// Pass a custom env object to env-var
const { get } = from({
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL
})

// Read variables using env-var API
const url = get('NEXT_PUBLIC_BASE_URL').asUrlString()
```

This is a little convoluted, but it's a quick workaround I've found works with the basic `npx create-next-app@latest` template.

**Comment by evanshortiss** [comment]
BTW @ted-dino, your explanation was perfectly good! Let me know if my answer is helpful.

**Comment by ted-dino** [comment]
worked like a charm. thank you @evanshortiss

**Comment by evanshortiss** [comment]
That's great! I referenced this issue for the next release. Will add a doc section for this issue.

**Comment by eparizzi-clevertech** [comment]
> That's great! I referenced this issue for the next release. Will add a doc section for this issue.

Has this doc section been added somewhere already? I'd like to see a full working example for Next.js.

**Comment by evanshortiss** [comment]
@eparizzi-clevertech I have some examples in the branch for the planned v8 release. Please [take a look here](https://github.com/evanshortiss/env-var/blob/typescript-refactor/EXAMPLE.md#react) and let me know if it's sufficient. Thanks!
