### ISSUE TITLE
When testing, env variables can't be change from the test

### ISSUE THREAD

**Issue by balibou** [evanshortiss/env-var#170]
**Describe the bug 🐛**
When I set process.env.NODE_ENV = 'staging' in the test, env.get('NODE_ENV').required().asString() returns 'test' and not 'staging'

**To Reproduce 📝**
```
describe('config', () => {
  const env = process.env;

  beforeEach(() => {
    jest.resetModules();
    process.env = { ...env };
  });

  afterEach(() => {
    process.env = env;
  });

  afterEach(() => {
    process.env = env;
  });

  it('should return env', () => {
    process.env.NODE_ENV = 'staging';
    const env = getEnv();
    expect(env).toBe('staging');
  });
});
```

```
import * as env from 'env-var';

export const getEnv = () => {
  return env.get('NODE_ENV').required().asString();
};

```

**Environment (please complete the following information) 💻:**
 - OS: MacOS Ventura 13.4
 - Runtime node.js
 - Version v18.15.0

**Comment by evanshortiss** [comment]
@balibou I'm just guessing since I don't have a full reproduction environment, but because you've loaded env-var using `import * as env from 'env-var';` it's changes Jest is making to `process.env`. 


Does it work if you do this?

```ts
import { from } from 'env-var';

// env is a process.env object
export const getEnv = (env) => {
   const { get } = from(env)
   
  return get('NODE_ENV').required().asString();
};
```

**Comment by evanshortiss** [comment]
Oh, and of course the test will need to be:


```ts
it('should return env', () => {
  process.env.NODE_ENV = 'staging';
  const env = getEnv(process.env);
  expect(env).toBe('staging');
});
```

**Comment by balibou** [comment]
All good thank you very much @evanshortiss !
