### ISSUE TITLE
Bug with `default` and `asEnum`

### ISSUE THREAD

**Issue by LBF38** [evanshortiss/env-var#171]
**Describe the bug 🐛**
I have found a bug when chaining `default` with `asEnum`.

**To Reproduce 📝**
```typescript
export const NODE_ENV = env
	.get("NODE_ENV")
	.default("development")
	.asEnum(["development", "production"]);
``` 

**Expected behaviour 🤷‍♂️🤷**
If the `NODE_ENV` is not defined, then it shouldn't error and should be defined as `development`.

**Screenshots 📷**
![image](https://github.com/evanshortiss/env-var/assets/96347823/bc57c2d5-527b-4e98-9271-223a4e6251f8)

**Environment (please complete the following information) 💻:**
 - OS: Linux (in Docker image)
 - Runtime: NodeJS
 - Version: 20.x

**Additional context**
N/A

workaround => changing `asEnum` by `asString`.

**Comment by evanshortiss** [comment]
@LBF38 can you share some more details? The code doesn't raise any error in my test environment:

```bash
cd /tmp
mkdir env-var
cd env-var
npm init -y
npm i env-var
touch index.js
```

Add code to index.js:

```js
const env = require('env-var')

const NODE_ENV= env
  .get("NODE_ENV")
  .default("development")
  .asEnum(["development", "production"]);

console.log(NODE_ENV)
```


Running this results in no error for me. 

The only way I receive an error is using these commands to start the script:

```bash
NODE_ENV='bad-value' node index.js
NODE_ENV='' node index.js
```

**Comment by evanshortiss** [comment]
The last example I shared `NODE_ENV=''` might be what you're facing. Setting `NODE_ENV` to an empty string means it is defined, but fails to match the specified enums.

**Comment by LBF38** [comment]
Hi, 
Thanks for the answer, yes I saw that too, it was a `NODE_ENV=` in my `.env` file that I forgot to delete, that's why I had this error ! 😄 Sorry for the unnecessary issue !

And thanks a lot for this useful lib ! Helps a lot to manage env vars in TypeScript ! 🙏

**Comment by evanshortiss** [comment]
You're welcome, and no worries!
