### ISSUE TITLE
Question: There is no documentation of where to place the env file or how to load it

### ISSUE THREAD

**Issue by mwakaambrose** [evanshortiss/env-var#19]
Could anybody provide and clarity on how to go about this?

**Comment by evanshortiss** [comment]
@mwakaambrose this module does not use an environment file. It reads environment variables in the system, or variables loaded by a module such as dotenv (this uses files).

If you're not too familiar with the concept here's an example on a Linux/Unix style machine command line. I set an environment variable and use it in a node program to print out `"Hello, ${NAME_VARIABLE}"`

```
$ export NAME_VARIABLE=evan

$ node -e "console.log('Hello, ' + process.env.NAME_VARIABLE)"
Hello, evan
```

This variable only applies to the current terminal. Depending on your system you'll need to see the best way to set variables.

Now, for your original question. If you want to use a file then you can combine this module and [dotenv](https://www.npmjs.com/package/dotenv) like so:

```js
require('dotenv').config() // this will read a .env file at the root of your repo

const env = require('env-var')

const name = env.get('NAME_VARIABLE').required().asString()
```

Here's a sample `.env` file:

```
NAME_VARIABLE=evan
```

Hope this helps. Feel free to comment back 😄
