### ISSUE TITLE
I see TypeScript but none is written in TypeScript nor ES Modules

### ISSUE THREAD

**Issue by motss** [evanshortiss/env-var#45]
I really hope to see this package to be written in ES Modules for tree shakable reason.

**Comment by evanshortiss** [comment]
@motss this module supports TypeScript, but is not exporting ES Modules. Node.js support for ES Modules is still [not stable](https://nodejs.org/api/esm.html) in v11.14.

Are you using this module in a web application so you need to minimise bundle size?

There seems to be ways to work around this using Babel,Rollup,Webpack etc. toolchains. Is this something you're familiar with and could provide some guidance on here?

**Comment by evanshortiss** [comment]
One thing I wonder. If this is converted to ES Modules, importing the `get` function, e.g `import { get } from 'env-var';` would import all getters (e.g `asString()` too).

So would other changes be necessary to optimise for tree shaking?

**Comment by motss** [comment]
You can only export a variable, a function, or a class in a module. When you mention getter, unless it is a static getter nothing will be allowed to be exported. It does not work like that.

For functions, if the function you export depends on another function in another module, it will be included as part of the export.

Hope this helps.

**Comment by evanshortiss** [comment]
`get` is a function exported by `env-var`. I'm not talking about generic getters 😄 

> For functions, if the function you export depends on another function in another module, it will be included as part of the export.

OK, so that's an issue right? If you do

```
import { get } from 'env-var'

const NODE_ENV = get('NODE_ENV').asString()
```

Will the tree shaking include:

* `get`
* `asString`

or will it include:

* `get`
* And all of these - https://github.com/evanshortiss/env-var/blob/master/lib/variable.js#L65-L112

I guess I'm asking "how smart is tree shaking" in modern JS tools?

**Comment by evanshortiss** [comment]
@motss any thoughts on this? Would you be interested in doing a little investigation on it. If not I can close this until it becomes more pressing.
