### ISSUE TITLE
Feature request: asArray()

### ISSUE THREAD

**Issue by henriklundgren** [evanshortiss/env-var#5]
Would be nice to have asArray() as well.

**Comment by evanshortiss** [comment]
@henriklundgren nice idea. Would you be able to provide some pseudo/sample code for how you'd like this to work?

I think the current `asJson` would work for some scenarios, but `asArray` could ensure the result is an Array and not an Object. For example, this is currently possible:

```js
var env = require('env-var');

// ARRAY is set to "[1, 2, 3, 4]"
// OBJECT is set to "{"name":"env-var"}"

var arr = env('ARRAY').asJson();
var obj = env('OBJECT').asJson();
```

But neither of these check that the parsed entry is truly and Object or an Array. So were you thinking this maybe?

```js
var env = require('env-var');

// ARRAY is set to "[1, 2, 3, 4]"
// OBJECT is set to "{"name":"env-var"}"

var arr = env('ARRAY').asArray();
var obj = env('OBJECT').asObject();

env('OBJECT').asArray(); // throws an error
```

**Comment by henriklundgren** [comment]
Atm I do;

```javascript
function asArray(str: string): string[] {
  return str.split(',');
}
asArray(env('LIST').required().asString());
```

```bash
$ env LIST=red,blue,green npm start
```

**Comment by evanshortiss** [comment]
@henriklundgren I see, would you be opposed to doing the following:

```
$ env LIST=[red,blue,green] npm start
```

and then this module could expose an _asArray_ function, and your code would be like so:

```
env('LIST').required().asArray()
```

If this doesn't work for you then perhaps a function named _asCommaSeparatedArray_ could be added. Thoughts?

**Comment by henriklundgren** [comment]
I believe csv's is more or less defacto standard to pass ArgumentList,
at least thats how I pass lists to the cli applications I use on daily basis.
I am reluctant to change that unless you are able to convince me.

**Comment by evanshortiss** [comment]
I'm with you, just trying to figure out the best overall approach.

JSON in environment variables is a little weird for sure, and many CLI tools just denote arrays using comma or space characters like you say. So perhaps we add a new function to `env-var` like so:

```
# your original setup
$env LIST=red,blue,green npm start
```

```js
var colours = env('LIST').required().asArrayWithDelimieter(','); 
```

Thoughts?

**Comment by evanshortiss** [comment]
Actually, just _asArray(',')` is fine, since we can also add `asJsonArray()` which will implement my original suggestion.

**Comment by henriklundgren** [comment]
Appreciate the follow ups,

I guess that works,
though,
for completeness sake,
may I through out a third alternative,

```javascript
asArray({
	delimiter: ‘,’, // any string
	type: 'csv', // enum [‘csv’, ‘json’]
})
```

**Comment by evanshortiss** [comment]
@henriklundgren can you explain the need for `type` with an example of what the environment variable should be for each?

My understanding of your example is that `type` would determine how `env-var` does the parsing, but for `json` there's no need for a delimiter, right?

I think we're almost there on figuring out a solid approach.

**Comment by henriklundgren** [comment]
Yes, `delimiter` would loose its meaning if `json`.

I guess mainly my attempt to avoid polluting the method name scope,
with names that means the same on face value level.
I.e. take a list of values (any) and turn it in to a javascript list (array).

```javascript
as[Array/List](type[, delimiter])
// or
as[Array/List]([type][, delimiter]) // all optional, default json
// or
asList(',')
asArray() // json, wouldnt this be the same as asJson()?
```

**Comment by evanshortiss** [comment]
Gotcha, I'm thinking we need 3 functions:

* asJsonObject (This is not related to this issue, but I need it)
* asJsonArray (Is somewhat related to this issue, will be needed in the future)
* asArray([delimiter])

I don't think "type" is necessary right now based on this discussion.

I can start on this later, unless you already have something done? 😄

**Comment by evanshortiss** [comment]
Released in version 2.4. Let me know how it is @henriklundgren  😄

**Comment by henriklundgren** [comment]
Thank you, works great, I can finally get rid of my little helper function. :tada:

**Comment by evanshortiss** [comment]
Great! TypeScript definitions are also available 🎉

**Comment by xavierchow** [comment]
Do you guys think it's a good idea to add trim for the asArray, because there might be spaces in the csv format env var for readability, e.g. `COLOR="red, greeb, blue"`

**Comment by evanshortiss** [comment]
@xavierchow I'd considered that, but decided against it to keep things simple. Might be able to support it via an option though.
