### ISSUE TITLE
URL validity

### ISSUE THREAD

**Issue by moltar** [evanshortiss/env-var#51]
I understand that the library is using `is-url` under the hook. But I think that package is a bit too simplistic.

> EnvVarError: env-var: "DATABASE_URL" should be a valid URL, but was "postgres://admin:password@localhost:5432"

This is a valid URL.

**Comment by evanshortiss** [comment]
@moltar agreed, this came up recently and I never actioned it. It seems like the `valid-url` module might be a better option since it seems to work with database URLs.

**Comment by evanshortiss** [comment]
I can make the change in the next 24 hours, but feel to PR if you like. Things I think need to be done are:

1. Use the `valid-url` module
2. Add tests for a few types of URL
3. Bump major version

I was thinking it might be worth supporting a protocol function/argument so users can say `asUrlString('http')`, but I think we can leave that out.

**Comment by moltar** [comment]
Seems like `valid-url` is not well maintained. Last release 6 years ago. And 12 open issues.

Why not Node's `url` [built-in package](https://nodejs.org/api/url.html)?

From the docs:

> A TypeError will be thrown if the input or base are not valid URLs. Note that an effort will be made to coerce the given values into strings.

The only "cons" I can think of is that it would need bundling for the front-end.

But I am not sure if the `env-var` is targetting front-end too?

The benefit of using `url` is that it could then return the actual URL object, rather than a string.

And then we can access scheme via `protocol` prop.

---

> I was thinking it might be worth supporting a protocol function/argument so users can say asUrlString('http'), but I think we can leave that out.

IMO this feels like feature creeping a bit, and seems like maybe outside the scope of this?

Maybe this can be generalized into some kind of method that can run custom validations?

```
// ignore the bad name
.asCustomMatcher((uri) => {
  if (uri.protocol !== 'http') {
    throw new Error('Must be http')
  }

  return true
})
```

**Comment by evanshortiss** [comment]
> IMO this feels like feature creeping a bit

Good to hear you agree!

> A TypeError will be thrown if the input or base are not valid URLs

Oh man, I totally overlooked that. The module already uses core `url`. Yeah, let's just do that 🎉 

> Maybe this can be generalized into some kind of method that can run custom validations

Could explore this in a separate issue 👍

**Comment by moltar** [comment]
Ok, I tried switching to `url`, but it turns out that almost anything is a valid URL.

I've tried supplying:

 - `null`
 - `undefined`
 - `1`
 - `/`
 - `asdasd`

to `parseUrl` method and it never throws.

I guess these are technically valid according to spec?

So, then the question is how useful that is?

Thoughts?

**Comment by evanshortiss** [comment]
Jeez. Not really useful, right?

Maybe it's possible to use the new URL API in JS spec? Though it would require a polyfill in Node.js 8 and below.

This works for example in Node.js 10+:

```js
> new URL('postgres://admin:password@localhost:5432')
URL {
  href: 'postgres://admin:password@localhost:5432',
  origin: 'null',
  protocol: 'postgres:',
  username: 'admin',
  password: 'password',
  host: 'localhost:5432',
  hostname: 'localhost',
  port: '5432',
  pathname: '',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' }
```

But these will fail:

```
// Notice the missing colon before "//"
new URL('postgres//admin:password@localhost:5432')
{ TypeError [ERR_INVALID_URL]: Invalid URL: postgres//admin:password@localhost:5432
    at onParseError (internal/url.js:240:17)
    at parse (internal/url.js:249:3)
    at new URL (internal/url.js:324:5) input: 'postgres//admin:password@localhost:5432' }

> new URL(undefined)
{ TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:240:17)
    at parse (internal/url.js:249:3)
    at new URL (internal/url.js:324:5) input: 'undefined' }

> new URL('undefined')
{ TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:240:17)
    at parse (internal/url.js:249:3)
    at new URL (internal/url.js:324:5) input: 'undefined' }

```

**Comment by evanshortiss** [comment]
@moltar this is improved in release 5.0.0. Now using the built-in URL class 😄 

Feel free to reopen if it's still an issue.
