### ISSUE TITLE
asArray should accept env-variable also with one element

### ISSUE THREAD

**Issue by gabrieloczkowski** [evanshortiss/env-var#56]
https://github.com/evanshortiss/env-var/blob/ae09f18b8bd45ed3562d532eebabb30a30cc575e/lib/accessors/array.js#L5-L13

Current behaviour:
`"value"` - throws error because of missing delimiter (bad)
`"value,"` - returns `["value,"]` (bad)

Expected result for both cases should be `["value"]`. That can be fixed by removing lines 8-10.

**Comment by gabrieloczkowski** [comment]
Created PR:
https://github.com/evanshortiss/env-var/pull/57

**Comment by tomsquest** [comment]
Same for non-existing and empty environment variables.

Currently, this throws : `process.env.EMPTY_VAR = ""; env.get("EMPTY_VAR").asArray())`.
Examples: https://repl.it/repls/WastefulHotpinkConfig

@gabrieloczkowski do you think your PR should/will handle an empty var ?

BTW, I was exactly, at the same moment, doing a test in a Repl for it! :)

**Comment by gabrieloczkowski** [comment]
@tomsquest after consideration I decided to handle empty vars (result `[]`) as it looks more proper way. 
We can finish it together if you want to help ;)

**Comment by gabrieloczkowski** [comment]
I added unit tests for changed logic.

**Comment by evanshortiss** [comment]
I never saw your comment in #16 @caccialdo, sorry about that!

I'm good with this PR. Nice work @gabrieloczkowski

**Comment by gabrieloczkowski** [comment]
@evanshortiss Since PR is merged we can close?

**Comment by evanshortiss** [comment]
Released in 5.0.0, thank you! 😄
