### ISSUE TITLE
Feature: ability to add custom accessors

### ISSUE THREAD

**Issue by todofixthis** [evanshortiss/env-var#71]
As a developer, I would like to define custom accessors, so that I can work with env vars in formats specific to my application's requirements.

For example:

```js
const env = from(process.env, {
  asNodes: (raiseError, value, type = Set) => {
    return new type(
      value.split(',')
        .map(s => s.trim())
        .map(s => s.split(':', 2))
        .map(([ip, port = 80]) => ({ ip, port }))
    )
  }
})

const bootnodes = env.get('BOOTNODES').asNodes()
```

Proposed acceptance criteria:
- A developer can call `from()` and provide an optional object as a second parameter.  The object defines additional accessors for any value returned by that instance's `get()`.
- If the name matches an existing accessor, the existing accessor is replaced by the new one for all subsequent calls to `env.get()`.

**Comment by evanshortiss** [comment]
@todofixthis I like this, there's a guide in the README for making a PR adding custom accessors, but sometimes they are application specific so this is great 👍

Will take a look at the PR

**Comment by todofixthis** [comment]
Per https://github.com/evanshortiss/env-var/pull/72#issuecomment-526772161 modifying the acceptance criteria so that extra accessors are provided as a parameter to `from()` rather than using a method to mutate the object state.
