### ISSUE TITLE
Property 'required' does not exist on type 'IPresentVariable'. ts(2339)

### ISSUE THREAD

**Issue by kenberkeley** [evanshortiss/env-var#95]
**Describe the bug 🐛**
As title.

**To Reproduce 📝**
Just copy the code from https://github.com/evanshortiss/env-var#variable

```js
const SECRET = env.get('SECRET', 'bad-secret').required(NODE_ENV === 'production').asString()
```

**Expected behaviour 🤷‍♂️🤷**
Should not complain about `Property 'required' does not exist on type 'IPresentVariable'. ts(2339)`

**Screenshots 📷**
![image](https://user-images.githubusercontent.com/13287948/73604204-d95d9080-45e0-11ea-9019-ab3438de63fa.png)

**Environment (please complete the following information) 💻:**
 - OS: macOS
 - Runtime: VS Code
 - Version: 1.41.1

**Additional context**

```js
// Works fine without setting the default value
const SECRET = env.get('SECRET').required(process.env.NODE_ENV === 'production').asString()
```

**Comment by evanshortiss** [comment]
@kenberkeley ah so this is a README error. If you put a default value, i.e "bad-secret" in this case, then `required` is not available since a default value was provided. Do you want to submit a README patch like this?

```
// If mode is production then this is required, else use default
const SECRET = env.get('SECRET').required(NODE_ENV === 'production').asString() || 'bad-secret'
```

Or do you think the current behavior is problematic?

**Comment by evanshortiss** [comment]
Of course, it can also be changed in the typings so you can call it since I don't think it would have any major side-effect and is probably safer.

**Comment by evanshortiss** [comment]
@kenberkeley I will fix this in 6.x coming soon. Leaving the issue open until that time.

**Comment by kenberkeley** [comment]
🙏🙏🙏

**Comment by evanshortiss** [comment]
@kenberkeley fixed in 6.x
